/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitaciones_paneles;

import java.awt.event.ActionEvent;

/**
 *
 * @author usuario
 */
public class ConsultarPrecio_Panel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarPrecio_Panel
     */
    public ConsultarPrecio_Panel() {
        initComponents();
        jLabelCambiarPrecioHabitacionesTItle.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRealizarCambios = new javax.swing.JButton();
        jLabelPrecioHabitacionesTitle = new javax.swing.JLabel();
        jTextFieldPrecioNuevo = new javax.swing.JTextField();
        jLabelCambiarPrecioHabitacionesTItle = new javax.swing.JLabel();
        jCoBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonConsultarPrecio = new javax.swing.JButton();
        label_ConsultaPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));

        jButtonRealizarCambios.setBackground(new java.awt.Color(29, 29, 29));
        jButtonRealizarCambios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonRealizarCambios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRealizarCambios.setText("Realizar Cambios");
        jButtonRealizarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarCambiosActionPerformed(evt);
            }
        });

        jLabelPrecioHabitacionesTitle.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabelPrecioHabitacionesTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioHabitacionesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecioHabitacionesTitle.setText("Consultar precio de habitaciones");

        jLabelCambiarPrecioHabitacionesTItle.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabelCambiarPrecioHabitacionesTItle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambiarPrecioHabitacionesTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCambiarPrecioHabitacionesTItle.setText("Cambiar precio de las habitaciones");

        jCoBoxTipoHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jCoBoxTipoHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCoBoxTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jCoBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble", "Matrimonial", "Suite Sencilla","Suite Presidencial" }));
        
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa el nuevo precio de la habitación.");

        jButtonConsultarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonConsultarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarPrecio.setText("Consultar");
        jButtonConsultarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPrecioActionPerformed(evt);
            }
        });

        label_ConsultaPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_ConsultaPrecio.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de habitacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPrecioHabitacionesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCambiarPrecioHabitacionesTItle, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jCoBoxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonConsultarPrecio))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldPrecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_ConsultaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButtonRealizarCambios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPrecioHabitacionesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCambiarPrecioHabitacionesTItle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jCoBoxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButtonConsultarPrecio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ConsultaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRealizarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }

    private String jButtonRealizarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarCambiosActionPerformed
        
        throw new UnsupportedOperationException("Unimplemented method 'jButtonConsultarPrecioActionPerformed'");
    }

    private String jButtonConsultarPrecioActionPerformed(ActionEvent evt) {
        
        throw new UnsupportedOperationException("Unimplemented method 'jButtonConsultarPrecioActionPerformed'");
    }

    private String obtenerTipo(javax.swing.JComboBox jCoBoxTipoHabitacion) {
        return jCoBoxTipoHabitacion.getSelectedItem().toString();
    }

    private String obtenerPrecioNuevo(javax.swing.JTextField jTextFieldPrecioNuevo) {
        return jTextFieldPrecioNuevo.getText();
    }

    public void ocultarModPrecio(){
        jLabelPrecioHabitacionesTitle.setText("Consultar precio de habitaciones");
        jTextFieldPrecioNuevo.setVisible(false);
        jButtonRealizarCambios.setVisible(false);
        jLabel2.setVisible(false);
        jLabelPrecioHabitacionesTitle.setVisible(true);
        jLabel3.setVisible(true);
        jCoBoxTipoHabitacion.setVisible(true);
        jButtonConsultarPrecio.setVisible(true);
        label_ConsultaPrecio.setVisible(true);
        this.repaint();
    }

    public void ocultarConsultaPrecio(){
        jLabelPrecioHabitacionesTitle.setText(jLabelCambiarPrecioHabitacionesTItle.getText());
        jLabel3.setVisible(true);
        jCoBoxTipoHabitacion.setVisible(true);
        jButtonConsultarPrecio.setVisible(false);
        label_ConsultaPrecio.setVisible(false);
        jLabel2.setVisible(true);
        jTextFieldPrecioNuevo.setVisible(true);
        jButtonRealizarCambios.setVisible(true);
        this.repaint();
    }
    // Variables declaration 
    private javax.swing.JButton jButtonConsultarPrecio;
    private javax.swing.JButton jButtonRealizarCambios;
    private javax.swing.JComboBox<String> jCoBoxTipoHabitacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCambiarPrecioHabitacionesTItle;
    private javax.swing.JLabel jLabelPrecioHabitacionesTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPrecioNuevo;
    private javax.swing.JLabel label_ConsultaPrecio;
    
}
