/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitaciones_paneles;

/**
 *
 * @author usuario
 */
public class ConsultarPrecio_Panel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarPrecio_Panel
     */
    public ConsultarPrecio_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRealizarCambios = new javax.swing.JButton();
        jLabelPrecioHabitacionesTitle = new javax.swing.JLabel();
        jTextFieldPrecioNuevo = new javax.swing.JTextField();
        jLabelCambiarPrecioHabitacionesTItle = new javax.swing.JLabel();
        jCoBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonConsultarPrecio = new javax.swing.JButton();
        label_ConsultaPrecio = new javax.swing.JLabel();
        jButtonModificarPrecioHabitacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRealizarCambios.setBackground(new java.awt.Color(29, 29, 29));
        jButtonRealizarCambios.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonRealizarCambios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRealizarCambios.setText("Realizar Cambios");
        jButtonRealizarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarCambiosActionPerformed(evt);
            }
        });
        add(jButtonRealizarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, 20));

        jLabelPrecioHabitacionesTitle.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabelPrecioHabitacionesTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioHabitacionesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecioHabitacionesTitle.setText("Consultar precio de habitaciones");
        add(jLabelPrecioHabitacionesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));
        add(jTextFieldPrecioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, -1));

        jLabelCambiarPrecioHabitacionesTItle.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabelCambiarPrecioHabitacionesTItle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCambiarPrecioHabitacionesTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCambiarPrecioHabitacionesTItle.setText("Cambiar precio de las habitaciones");
        add(jLabelCambiarPrecioHabitacionesTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jCoBoxTipoHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jCoBoxTipoHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCoBoxTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jCoBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCoBoxTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa el nuevo precio de la habitación.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jButtonConsultarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonConsultarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarPrecio.setText("Consultar");
        add(jButtonConsultarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        label_ConsultaPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_ConsultaPrecio.setForeground(new java.awt.Color(255, 255, 255));
        add(label_ConsultaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 590, 360));

        jButtonModificarPrecioHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jButtonModificarPrecioHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonModificarPrecioHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarPrecioHabitacion.setText("Modificar");
        add(jButtonModificarPrecioHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de habitacion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRealizarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarPrecio;
    private javax.swing.JButton jButtonModificarPrecioHabitacion;
    private javax.swing.JButton jButtonRealizarCambios;
    private javax.swing.JComboBox<String> jCoBoxTipoHabitacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCambiarPrecioHabitacionesTItle;
    private javax.swing.JLabel jLabelPrecioHabitacionesTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPrecioNuevo;
    private javax.swing.JLabel label_ConsultaPrecio;
    // End of variables declaration//GEN-END:variables
}
