/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitaciones_paneles;

/**
 *
 * @author usuario
 */
public class PanelVerificar_CambiarEstado extends javax.swing.JPanel {

    /**
     * Creates new form PanelVerificarReserva
     */
    public PanelVerificar_CambiarEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButtonConsultarEstado = new javax.swing.JButton();
        label_ConsultaDispo = new javax.swing.JLabel();
        label_ConsultaDispo1 = new javax.swing.JLabel();
        jTextFieldPrecioNuevo = new javax.swing.JTextField();
        jButtonCambiarEstado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 650, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Disponibilidad de Habitacion");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jButtonConsultarEstado.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonConsultarEstado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarEstado.setText("Consultar");
        add(jButtonConsultarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        label_ConsultaDispo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_ConsultaDispo.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ConsultaDispo.setText("Cambiar Estado de la Habitación.");
        add(label_ConsultaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        label_ConsultaDispo1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_ConsultaDispo1.setForeground(new java.awt.Color(255, 255, 255));
        add(label_ConsultaDispo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 290, 30));
        add(jTextFieldPrecioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        jButtonCambiarEstado.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCambiarEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCambiarEstado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarEstado.setText("Cambiar");
        add(jButtonCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa el numero de la habitación: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Ocupado");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Reservado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Disponible");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarEstado;
    private javax.swing.JButton jButtonConsultarEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPrecioNuevo;
    private javax.swing.JLabel label_ConsultaDispo;
    private javax.swing.JLabel label_ConsultaDispo1;
    // End of variables declaration//GEN-END:variables
}
