/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitaciones_paneles;

/**
 *
 * @author usuario
 */
public class Panel_HabitacionesOpciones extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Options
     */
    public Panel_HabitacionesOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonServiciosDeHabitacion = new javax.swing.JButton();
        jButtonListarHabitaciones = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonConsultarPrecio = new javax.swing.JButton();
        jButtonModificarPrecio = new javax.swing.JButton();
        jButtonCambiarEstado1 = new javax.swing.JButton();
        jButtonVerificarDispo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_Interno_Options = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(810, 640));
        setMinimumSize(new java.awt.Dimension(810, 640));
        setPreferredSize(new java.awt.Dimension(810, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonServiciosDeHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jButtonServiciosDeHabitacion.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonServiciosDeHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonServiciosDeHabitacion.setText("Servicios Ofrecidos");
        add(jButtonServiciosDeHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, -1));

        jButtonListarHabitaciones.setBackground(new java.awt.Color(29, 29, 29));
        jButtonListarHabitaciones.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonListarHabitaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarHabitaciones.setText("Buscar Habitaciones");
        jButtonListarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarHabitacionesActionPerformed(evt);
            }
        });
        add(jButtonListarHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, -1));

        jButtonBack.setBackground(new java.awt.Color(29, 29, 29));
        jButtonBack.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-izquierda.png"))); // NOI18N
        add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 120, 60));

        jButtonConsultarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarPrecio.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonConsultarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarPrecio.setText("Consultar Precio");
        jButtonConsultarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPrecioActionPerformed(evt);
            }
        });
        add(jButtonConsultarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, -1));

        jButtonModificarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonModificarPrecio.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonModificarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarPrecio.setText("Modificar Precio");
        add(jButtonModificarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, -1));

        jButtonCambiarEstado1.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCambiarEstado1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonCambiarEstado1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarEstado1.setText("Cambiar Estado Habitacion");
        add(jButtonCambiarEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 210, -1));

        jButtonVerificarDispo.setBackground(new java.awt.Color(29, 29, 29));
        jButtonVerificarDispo.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonVerificarDispo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerificarDispo.setText("Verificar Estado Habitacion");
        jButtonVerificarDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarDispoActionPerformed(evt);
            }
        });
        add(jButtonVerificarDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Habitaciones");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("El Descanso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edificio.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 130));

        panel_Interno_Options.setBackground(new java.awt.Color(29, 29, 29));
        panel_Interno_Options.setMaximumSize(new java.awt.Dimension(640, 580));
        panel_Interno_Options.setMinimumSize(new java.awt.Dimension(640, 580));
        panel_Interno_Options.setName(""); // NOI18N
        panel_Interno_Options.setPreferredSize(new java.awt.Dimension(640, 580));

        javax.swing.GroupLayout panel_Interno_OptionsLayout = new javax.swing.GroupLayout(panel_Interno_Options);
        panel_Interno_Options.setLayout(panel_Interno_OptionsLayout);
        panel_Interno_OptionsLayout.setHorizontalGroup(
            panel_Interno_OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panel_Interno_OptionsLayout.setVerticalGroup(
            panel_Interno_OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        add(panel_Interno_Options, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 580, 640));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarHabitacionesActionPerformed

    private void jButtonVerificarDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerificarDispoActionPerformed

    private void jButtonConsultarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCambiarEstado1;
    private javax.swing.JButton jButtonConsultarPrecio;
    private javax.swing.JButton jButtonListarHabitaciones;
    private javax.swing.JButton jButtonModificarPrecio;
    private javax.swing.JButton jButtonServiciosDeHabitacion;
    private javax.swing.JButton jButtonVerificarDispo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel_Interno_Options;
    // End of variables declaration//GEN-END:variables
}
