/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clientes_paneles;

/**
 *
 * @author usuario
 */
public class Panel_TotalCliente extends javax.swing.JPanel {

    /**
     * Creates new form Panel_TotalCliente
     */
    public Panel_TotalCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_IDcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCoBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonGenerarTotal = new javax.swing.JButton();
        jTextNumDias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        label_TotalApagarTitle = new javax.swing.JLabel();
        label_Listar1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jText_IDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 210, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa la identificación del cliente:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jCoBoxTipoHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jCoBoxTipoHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCoBoxTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jCoBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCoBoxTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de habitacion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jButtonGenerarTotal.setBackground(new java.awt.Color(29, 29, 29));
        jButtonGenerarTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonGenerarTotal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerarTotal.setText("Consultar");
        add(jButtonGenerarTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));
        add(jTextNumDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresa el numero de dias de estadia:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        label_TotalApagarTitle.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_TotalApagarTitle.setForeground(new java.awt.Color(255, 255, 255));
        label_TotalApagarTitle.setText("El total a pagar para el cliente es de:");
        add(label_TotalApagarTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 550, 30));

        label_Listar1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_Listar1.setForeground(new java.awt.Color(255, 255, 255));
        add(label_Listar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 550, 210));

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Generar total a cliente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 640, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarTotal;
    private javax.swing.JComboBox<String> jCoBoxTipoHabitacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextNumDias;
    private javax.swing.JTextField jText_IDcliente;
    private javax.swing.JLabel label_Listar1;
    private javax.swing.JLabel label_TotalApagarTitle;
    // End of variables declaration//GEN-END:variables
}
