/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clientes_paneles;

/**
 *
 * @author usuario
 */
public class Panel_IdentificarCliente extends javax.swing.JPanel {

    /**
     * Creates new form Panel_IdentificarCliente
     */
    public Panel_IdentificarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButtonConsultarEstado = new javax.swing.JButton();
        label_ConsultaDispo = new javax.swing.JLabel();
        label_TipoCliente = new javax.swing.JLabel();
        jTextFieldPrecioNuevo = new javax.swing.JTextField();
        jLabelNombreCliente = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelDescuentoParaCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 20));

        jButtonConsultarEstado.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonConsultarEstado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarEstado.setText("Consultar");
        add(jButtonConsultarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        label_ConsultaDispo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_ConsultaDispo.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ConsultaDispo.setText("Buscar Cliente");
        add(label_ConsultaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 30));

        label_TipoCliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_TipoCliente.setForeground(new java.awt.Color(255, 255, 255));
        add(label_TipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 290, 30));
        add(jTextFieldPrecioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, -1));

        jLabelNombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 480, 40));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Habitual");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Esporadico");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa la identificación del cliente:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabelDescuentoParaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelDescuentoParaCliente.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabelDescuentoParaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 560, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("El cliente:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("El cliente tiene un descuento de:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo de cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescuentoParaCliente;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldPrecioNuevo;
    private javax.swing.JLabel label_ConsultaDispo;
    private javax.swing.JLabel label_TipoCliente;
    // End of variables declaration//GEN-END:variables
}
