/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clientes_paneles;

/**
 *
 * @author usuario
 */
public class PanelDescuentos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDescuentos
     */
    public PanelDescuentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        label_ConsultaDispo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextNewDescuento = new javax.swing.JTextField();
        jButtonAceptarNewDescuento = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelDescuento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 650, 20));

        label_ConsultaDispo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_ConsultaDispo.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ConsultaDispo.setText("Descuentos para los clientes habituales");
        add(label_ConsultaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 640, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Indica el nuevo valor");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 140, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 20));
        add(jTextNewDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, -1));

        jButtonAceptarNewDescuento.setBackground(new java.awt.Color(29, 29, 29));
        jButtonAceptarNewDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptarNewDescuento.setText("Aceptar");
        add(jButtonAceptarNewDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 650, 20));

        jLabelDescuento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelDescuento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 620, 40));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("El valor de descuento ofrecido para los clientes habituales es de:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modificar el valor de descuento ofrecido a los clientes habituales:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 600, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarNewDescuento;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDescuento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextNewDescuento;
    private javax.swing.JLabel label_ConsultaDispo;
    // End of variables declaration//GEN-END:variables
}
