/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package informes_paneles;

/**
 *
 * @author usuario
 */
public class DatosEstadisticosPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatosEstadisticosPanel
     */
    public DatosEstadisticosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        label_ConsultaDispo = new javax.swing.JLabel();
        jLabelPorcentaje = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonConsultarConsolidado = new javax.swing.JButton();
        mes_Seleccionado = new javax.swing.JComboBox<>();
        label_Consolidado = new javax.swing.JLabel();
        jLabelServicioMasSolicitado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 650, 20));

        label_ConsultaDispo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_ConsultaDispo.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ConsultaDispo.setText("Informe General");
        add(label_ConsultaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jLabelPorcentaje.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabelPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 150, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Porcentaje de Ocupacion En el Mes de ___ : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Porcentaje de ocupacion del hotel en el Mes de:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jButtonConsultarConsolidado.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarConsolidado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonConsultarConsolidado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarConsolidado.setText("Consultar");
        add(jButtonConsultarConsolidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 20));

        mes_Seleccionado.setBackground(new java.awt.Color(29, 29, 29));
        mes_Seleccionado.setForeground(new java.awt.Color(255, 255, 255));
        mes_Seleccionado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mes_Seleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_SeleccionadoActionPerformed(evt);
            }
        });
        add(mes_Seleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        label_Consolidado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_Consolidado.setForeground(new java.awt.Color(255, 255, 255));
        label_Consolidado.setText("Servicio Mas Solicitado:");
        add(label_Consolidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 20));
        add(jLabelServicioMasSolicitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, 20));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 590, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void mes_SeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_SeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes_SeleccionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarConsolidado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPorcentaje;
    private javax.swing.JLabel jLabelServicioMasSolicitado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_Consolidado;
    private javax.swing.JLabel label_ConsultaDispo;
    private javax.swing.JComboBox<String> mes_Seleccionado;
    // End of variables declaration//GEN-END:variables
}
