/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package informes_paneles;

/**
 *
 * @author usuario
 */
public class Panel_VentasXmes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_VentasXmes
     */
    public Panel_VentasXmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_ConsultaDispo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCalcularVentaxMes = new javax.swing.JButton();
        mes_Seleccionado = new javax.swing.JComboBox<>();
        label_CalculadoVentas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(640, 640));
        setMinimumSize(new java.awt.Dimension(640, 640));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelMes.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ventas en el mes de:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 650, 20));

        label_ConsultaDispo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_ConsultaDispo.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ConsultaDispo.setText("Calcular Ventas Por Meses");
        add(label_ConsultaDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecciona el mes al que deseas calcular las ventas: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jButtonCalcularVentaxMes.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCalcularVentaxMes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCalcularVentaxMes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcularVentaxMes.setText("Consultar");
        add(jButtonCalcularVentaxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 20));

        mes_Seleccionado.setBackground(new java.awt.Color(29, 29, 29));
        mes_Seleccionado.setForeground(new java.awt.Color(255, 255, 255));
        mes_Seleccionado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mes_Seleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_SeleccionadoActionPerformed(evt);
            }
        });
        add(mes_Seleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        label_CalculadoVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_CalculadoVentas.setForeground(new java.awt.Color(255, 255, 255));
        add(label_CalculadoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 550, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void mes_SeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_SeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes_SeleccionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularVentaxMes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_CalculadoVentas;
    private javax.swing.JLabel label_ConsultaDispo;
    private javax.swing.JComboBox<String> mes_Seleccionado;
    // End of variables declaration//GEN-END:variables
}
