/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package habitaciones_paneles;

/**
 *
 * @author usuario
 */
public class Panel_HabitacionesOpciones extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Options
     */
    public Panel_HabitacionesOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonListarHabitaciones = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonConsultarPrecio = new javax.swing.JButton();
        jButtonCambiarEstado = new javax.swing.JButton();
        jButtonModificarPrecio = new javax.swing.JButton();
        jButtonVerificarDispo1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_Interno_Options = new javax.swing.JPanel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(980, 640));
        setMinimumSize(new java.awt.Dimension(980, 640));
        setPreferredSize(new java.awt.Dimension(980, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonListarHabitaciones.setBackground(new java.awt.Color(29, 29, 29));
        jButtonListarHabitaciones.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonListarHabitaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListarHabitaciones.setText("Listar Habitaciones");
        jButtonListarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarHabitacionesActionPerformed(evt);
            }
        });
        add(jButtonListarHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jButtonBack.setBackground(new java.awt.Color(29, 29, 29));
        jButtonBack.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 120, 40));

        jButtonConsultarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonConsultarPrecio.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonConsultarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarPrecio.setText("Consultar Precio Habitacion");
        add(jButtonConsultarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, -1));

        jButtonCambiarEstado.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCambiarEstado.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonCambiarEstado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCambiarEstado.setText("Cambiar Estado Habitacion");
        add(jButtonCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jButtonModificarPrecio.setBackground(new java.awt.Color(29, 29, 29));
        jButtonModificarPrecio.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonModificarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarPrecio.setText("Modificar Precio");
        add(jButtonModificarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButtonVerificarDispo1.setBackground(new java.awt.Color(29, 29, 29));
        jButtonVerificarDispo1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jButtonVerificarDispo1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerificarDispo1.setText("Verificar Disponibilidad");
        add(jButtonVerificarDispo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Habitaciones");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hotel Budapest");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edificio.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));

        panel_Interno_Options.setBackground(new java.awt.Color(29, 29, 29));
        panel_Interno_Options.setMaximumSize(new java.awt.Dimension(810, 650));
        panel_Interno_Options.setMinimumSize(new java.awt.Dimension(810, 650));
        panel_Interno_Options.setName(""); // NOI18N

        javax.swing.GroupLayout panel_Interno_OptionsLayout = new javax.swing.GroupLayout(panel_Interno_Options);
        panel_Interno_Options.setLayout(panel_Interno_OptionsLayout);
        panel_Interno_OptionsLayout.setHorizontalGroup(
            panel_Interno_OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        panel_Interno_OptionsLayout.setVerticalGroup(
            panel_Interno_OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        add(panel_Interno_Options, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarHabitacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCambiarEstado;
    private javax.swing.JButton jButtonConsultarPrecio;
    private javax.swing.JButton jButtonListarHabitaciones;
    private javax.swing.JButton jButtonModificarPrecio;
    private javax.swing.JButton jButtonVerificarDispo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel_Interno_Options;
    // End of variables declaration//GEN-END:variables
}
