package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class JpanelModulos extends javax.swing.JPanel {

    /**
     * Creates new form JpanelModulos
     */
    public JpanelModulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFacturacion = new javax.swing.JButton();
        jButtonHabitacion = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonBackTologin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelUserWelcome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(980, 640));
        setMinimumSize(new java.awt.Dimension(980, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFacturacion.setBackground(new java.awt.Color(29, 29, 29));
        jButtonFacturacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFacturacion.setText("Facturacion");
        add(jButtonFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 20));

        jButtonHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jButtonHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHabitacion.setText("Habitaciones");
        add(jButtonHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 20));

        jButtonCliente.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setText("Cliente");
        add(jButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jButtonReservas.setBackground(new java.awt.Color(29, 29, 29));
        jButtonReservas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonReservas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservas.setText("Reservar");
        add(jButtonReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 20));

        jButtonBackTologin.setBackground(new java.awt.Color(29, 29, 29));
        jButtonBackTologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        add(jButtonBackTologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 100, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edificio.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 130));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hotel Budapest");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));

        labelUserWelcome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelUserWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelUserWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserWelcome.setText("Bienvenido al sistema del Hotel Budapest");
        add(labelUserWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 9, 600, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackTologin;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonFacturacion;
    private javax.swing.JButton jButtonHabitacion;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelUserWelcome;
    // End of variables declaration//GEN-END:variables
}
