package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class JpanelModulos extends javax.swing.JPanel {

    /**
     * Creates new form JpanelModulos
     */
    public JpanelModulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInformes1 = new javax.swing.JButton();
        jButtonInformes = new javax.swing.JButton();
        jButtonCheckIn = new javax.swing.JButton();
        jButtonCheckOut = new javax.swing.JButton();
        jButtonHabitacion = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonBackTologin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelUserWelcome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 29, 29));
        setMaximumSize(new java.awt.Dimension(810, 640));
        setMinimumSize(new java.awt.Dimension(810, 640));
        setPreferredSize(new java.awt.Dimension(810, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInformes1.setBackground(new java.awt.Color(29, 29, 29));
        jButtonInformes1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonInformes1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInformes1.setText("Gestionar Perfiles");
        add(jButtonInformes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 130, 20));

        jButtonInformes.setBackground(new java.awt.Color(29, 29, 29));
        jButtonInformes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonInformes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInformes.setText("Informes");
        add(jButtonInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 100, 20));

        jButtonCheckIn.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCheckIn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCheckIn.setText("Check-In");
        add(jButtonCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 100, 20));

        jButtonCheckOut.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCheckOut.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCheckOut.setText("Check-Out");
        add(jButtonCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 20));

        jButtonHabitacion.setBackground(new java.awt.Color(29, 29, 29));
        jButtonHabitacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHabitacion.setText("Habitaciones");
        add(jButtonHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        jButtonCliente.setBackground(new java.awt.Color(29, 29, 29));
        jButtonCliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setText("Cliente");
        add(jButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 270, 100, -1));

        jButtonReservas.setBackground(new java.awt.Color(29, 29, 29));
        jButtonReservas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonReservas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservas.setText("Reservar");
        add(jButtonReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 20));

        jButtonBackTologin.setBackground(new java.awt.Color(29, 29, 29));
        jButtonBackTologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-izquierda.png"))); // NOI18N
        add(jButtonBackTologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 100, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edificio.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 130));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("El Descanso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));

        jPanel1.setBackground(new java.awt.Color(29, 29, 29));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 640));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUserWelcome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelUserWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelUserWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUserWelcome.setText("Bienvenido al sistema del Hotel El Descanso");
        jPanel1.add(labelUserWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 10, 750, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackTologin;
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonCheckOut;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonHabitacion;
    private javax.swing.JButton jButtonInformes;
    private javax.swing.JButton jButtonInformes1;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUserWelcome;
    // End of variables declaration//GEN-END:variables
}
